# Generated by Django 5.2.3 on 2025-07-06 09:02
from typing import List

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = None

    dependencies = list[dict]()

    operations = [
        migrations.CreateModel(
            name="Coordinates",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("label", models.CharField(max_length=255)),
            ],
        ),
    ]
